name: Keep FerBot API Warm

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Curl health
        run: |
          curl -sS https://ferbot-api.onrender.com/health || true

